apiVersion: v1
kind: Service
metadata:
  name: {{ include "accent.fullname" . }}
  labels:
    {{- include "accent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "accent.selectorLabels" . | nindent 4 }}
